#!/bin/sh

NAME="ssdsplash"
DAEMON="/usr/bin/$NAME"
PIDFILE="/var/run/$NAME.pid"
# Uncomment and modify for alternate I2C address:
# DAEMON_ARGS="-a 0x3D"

start() {
    printf "Starting $NAME: "
    start-stop-daemon -S -q -p $PIDFILE -x $DAEMON -b -m -- $DAEMON_ARGS
    if [ $? = 0 ]; then
        echo "OK"
    else
        echo "FAIL"
    fi
}

stop() {
    printf "Stopping $NAME: "
    # Send quit message to daemon
    /usr/bin/ssdsplash-send -t quit 2>/dev/null
    sleep 1
    start-stop-daemon -K -q -p $PIDFILE
    if [ $? = 0 ]; then
        echo "OK"
    else
        echo "FAIL"
    fi
    rm -f $PIDFILE
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?